# Generated by Django 5.1.3 on 2025-11-29 22:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_id', models.CharField(db_index=True, help_text='Learning path ID from MongoDB CourseRecommendation', max_length=100)),
                ('lesson_id', models.CharField(db_index=True, help_text='Lesson ID within the learning path', max_length=200)),
                ('passing_score_percentage', models.IntegerField(default=70, help_text='Minimum score required to pass (default: 70%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('num_questions', models.IntegerField(default=5, help_text='Number of questions in this quiz', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('content_scraped', models.BooleanField(default=False, help_text='Whether actual lesson content was scraped for question generation')),
                ('content_source', models.CharField(blank=True, help_text='Source of scraped content (youtube_transcript, article, github, metadata)', max_length=50, null=True)),
                ('scraped_content_hash', models.CharField(blank=True, help_text='Hash of scraped content to detect changes', max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cache_until', models.DateTimeField(help_text='When to regenerate this quiz (30 days from creation)')),
                ('lesson_title', models.CharField(blank=True, max_length=300)),
                ('lesson_platform', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Lesson Quiz',
                'verbose_name_plural': 'Lesson Quizzes',
                'db_table': 'learning_content_lesson_quiz',
                'indexes': [models.Index(fields=['path_id', 'lesson_id'], name='learning_co_path_id_484fb0_idx'), models.Index(fields=['cache_until'], name='learning_co_cache_u_4db64f_idx')],
                'constraints': [models.UniqueConstraint(fields=('path_id', 'lesson_id'), name='unique_quiz_per_lesson')],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.IntegerField(default=1, help_text='Which attempt is this (1, 2, 3...)')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken_seconds', models.IntegerField(blank=True, help_text='Total time taken to complete (seconds)', null=True)),
                ('score_percentage', models.FloatField(default=0.0, help_text='Score as percentage (0-100)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('total_points_earned', models.IntegerField(default=0)),
                ('total_points_possible', models.IntegerField(default=0)),
                ('passed', models.BooleanField(default=False, help_text='Whether user passed (score >= passing_score_percentage)')),
                ('is_best_attempt', models.BooleanField(default=False, help_text="Is this the user's best scoring attempt?")),
                ('quiz', models.ForeignKey(help_text='Quiz being attempted', on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning_content.lessonquiz')),
                ('user', models.ForeignKey(help_text='User taking the quiz', on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quiz Attempt',
                'verbose_name_plural': 'Quiz Attempts',
                'db_table': 'learning_content_quiz_attempt',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Display order (0-indexed)')),
                ('question_text', models.TextField(help_text='The question text')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('code', 'Code Question'), ('fill_blank', 'Fill in the Blank'), ('matching', 'Matching'), ('ordering', 'Ordering')], default='multiple_choice', max_length=20)),
                ('options', models.JSONField(default=dict, help_text='Question options and correct answer (structure varies by type)')),
                ('correct_answer', models.TextField(help_text='Correct answer or grading criteria')),
                ('explanation', models.TextField(blank=True, help_text='Explanation shown after answering (right or wrong)')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('blooms_level', models.CharField(blank=True, help_text='remember, understand, apply, analyze, evaluate, create', max_length=20)),
                ('points', models.IntegerField(default=1, help_text='Points for this question (default: 1)', validators=[django.core.validators.MinValueValidator(1)])),
                ('quiz', models.ForeignKey(help_text='Quiz this question belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning_content.lessonquiz')),
            ],
            options={
                'verbose_name': 'Quiz Question',
                'verbose_name_plural': 'Quiz Questions',
                'db_table': 'learning_content_quiz_question',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField(blank=True, help_text="User's answer (text, index, JSON for complex answers)")),
                ('is_correct', models.BooleanField(default=False, help_text='Whether the answer was correct')),
                ('points_earned', models.IntegerField(default=0, help_text='Points earned for this answer')),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('time_taken_seconds', models.IntegerField(blank=True, help_text='Time taken to answer this question', null=True)),
                ('ai_feedback', models.TextField(blank=True, help_text='AI-generated feedback on the answer')),
                ('attempt', models.ForeignKey(help_text='Quiz attempt this response belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='learning_content.quizattempt')),
                ('question', models.ForeignKey(help_text='Question being answered', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='learning_content.quizquestion')),
            ],
            options={
                'verbose_name': 'Question Response',
                'verbose_name_plural': 'Question Responses',
                'db_table': 'learning_content_question_response',
                'ordering': ['question__order'],
            },
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', 'quiz'], name='learning_co_user_id_d6cf04_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', '-started_at'], name='learning_co_user_id_addf07_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['quiz', 'user', '-attempt_number'], name='learning_co_quiz_id_c15fa1_idx'),
        ),
        migrations.AddIndex(
            model_name='quizquestion',
            index=models.Index(fields=['quiz', 'order'], name='learning_co_quiz_id_e17f1c_idx'),
        ),
        migrations.AddIndex(
            model_name='questionresponse',
            index=models.Index(fields=['attempt', 'question'], name='learning_co_attempt_eb9b10_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionresponse',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_response_per_attempt_question'),
        ),
    ]
