# Generated by Django 5.1.3 on 2025-09-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradvy_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='Employee ID (Optional)'),
        ),
    ]
