# Generated by Django 5.1.3 on 2025-09-06 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradvy_auth', '0002_make_employee_id_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='employee_id',
        ),
    ]
