# Generated by Django 5.1.3 on 2025-09-07 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradvy_auth', '0003_remove_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Unique password reset token', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When the token expires')),
                ('used', models.BooleanField(default=False, help_text='Whether this token has been used')),
                ('used_at', models.DateTimeField(blank=True, help_text='When the token was used', null=True)),
            ],
            options={
                'verbose_name': 'Password Reset Token',
                'verbose_name_plural': 'Password Reset Tokens',
                'db_table': 'accounts_password_reset_token',
            },
        ),
        migrations.AlterModelOptions(
            name='backupcode',
            options={'verbose_name': 'Backup Code', 'verbose_name_plural': 'Backup Codes'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterField(
            model_name='backupcode',
            name='code',
            field=models.CharField(help_text='Unique backup code string', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='backupcode',
            name='used',
            field=models.BooleanField(default=False, help_text='Whether this code has been used'),
        ),
        migrations.AlterField(
            model_name='backupcode',
            name='used_at',
            field=models.DateTimeField(blank=True, help_text='When the code was used', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='backup_codes_remaining',
            field=models.PositiveIntegerField(default=10, help_text='Number of unused backup codes'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(default='en', help_text="User's preferred language code", max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text="User's contact phone number", max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='UTC', help_text="User's preferred timezone", max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='totp_enabled',
            field=models.BooleanField(default=False, help_text='Legacy TOTP status field'),
        ),
        migrations.AddIndex(
            model_name='backupcode',
            index=models.Index(fields=['user', 'used'], name='accounts_ba_user_id_d89e44_idx'),
        ),
        migrations.AddIndex(
            model_name='backupcode',
            index=models.Index(fields=['code'], name='accounts_ba_code_1ef65d_idx'),
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['user'], name='accounts_pa_user_id_842a67_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['token'], name='accounts_pa_token_3e0820_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['expires_at'], name='accounts_pa_expires_682fbf_idx'),
        ),
    ]
