# Generated by Django 5.1.3 on 2025-09-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradvy_auth', '0004_passwordresettoken_alter_backupcode_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text="User's bio/about me section", max_length=500),
        ),
    ]
