# Generated by Django 5.1.3 on 2025-09-08 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradvy_auth', '0005_userprofile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('login_mfa_required', 'Login - MFA Required'), ('logout', 'Logout'), ('register', 'Registration'), ('password_change', 'Password Change'), ('password_reset_requested', 'Password Reset Requested'), ('password_reset_confirmed', 'Password Reset Confirmed'), ('mfa_enroll', 'MFA Enrolled'), ('mfa_verify', 'MFA Verification'), ('mfa_disable', 'MFA Disabled'), ('backup_codes_viewed', 'Backup Codes Viewed'), ('backup_codes_regenerated', 'Backup Codes Regenerated'), ('profile_updated', 'Profile Updated'), ('profile_update_failed', 'Profile Update Failed'), ('session_revoked', 'Session Revoked'), ('session_created', 'Session Created')], help_text='Type of authentication event', max_length=50)),
                ('success', models.BooleanField(help_text='Whether the event was successful')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address from which event occurred')),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from browser')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional event details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='User associated with the event', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Authentication Event',
                'verbose_name_plural': 'Authentication Events',
                'db_table': 'accounts_auth_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'event_type'], name='accounts_au_user_id_2e6f8b_idx'), models.Index(fields=['created_at'], name='accounts_au_created_1a0216_idx'), models.Index(fields=['ip_address'], name='accounts_au_ip_addr_f4ed20_idx'), models.Index(fields=['event_type', 'success'], name='accounts_au_event_t_a0395d_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Unique session identifier', max_length=255, unique=True)),
                ('session_key', models.CharField(blank=True, help_text='Django session key', max_length=40, null=True)),
                ('jwt_jti', models.CharField(blank=True, help_text='JWT token ID', max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address from which session was created')),
                ('user_agent', models.TextField(help_text='User agent string from browser')),
                ('device_info', models.JSONField(blank=True, default=dict, help_text='Parsed device information')),
                ('location_info', models.JSONField(blank=True, default=dict, help_text='Location information')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(help_text='When the session expires')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the session is currently active')),
                ('is_current', models.BooleanField(default=False, help_text='Whether this is the current session')),
                ('revoked_at', models.DateTimeField(blank=True, help_text='When the session was revoked', null=True)),
                ('revoked_by', models.CharField(blank=True, help_text='Who revoked the session', max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'db_table': 'accounts_user_session',
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='accounts_us_user_id_f3bc3f_idx'), models.Index(fields=['session_key'], name='accounts_us_session_5ce38e_idx'), models.Index(fields=['jwt_jti'], name='accounts_us_jwt_jti_a19ca4_idx'), models.Index(fields=['expires_at'], name='accounts_us_expires_89e160_idx')],
            },
        ),
    ]
